bob = User.create(username: "Bingo_Bob")
nash = User.create(username: "John_Nash")

p1 = Puzzle.create(content: "But soft! What light through yonder window breaks? It is the east, and Juliet is the sun.", author: "William Shakespeare", source: "Romeo and Juliet", difficulty: 1)
p2 = Puzzle.create(content: "It was the best of times, it was the worst of times.", author: "Charles Dickens", source: "A Tale of Two Cities", difficulty: 1)
p3 = Puzzle.create(content: "All happy families are alike; each unhappy family is unhappy in its own way.", author: "Leo Tolstoy", source: "Anna Karenina", difficulty: 1)
p4 = Puzzle.create(content: "The fact that a great many people believe something is no guarantee of its truth.", author: "W. Somerset Maugham", source: "The Razor's Edge", difficulty: 1)
p5 = Puzzle.create(content: "At sunrise everything is luminous but not clear. It is those we live with and love and should know who elude us. You can love completely without complete understanding.", author: "Norman Maclean", source: "A River Runs Through It", difficulty: 1)
p6 = Puzzle.create(content: "We cross our bridges when we come to them and burn them behind us, with nothing to show for our progress except a memory of the smell of smoke, and a presumption that once our eyes watered.", author: "Tom Stoppard", source: "Rosencrantz and Guildenstern Are Dead", difficulty: 1)
p7 = Puzzle.create(content: "The greater the scientific advance, the more primitive the fear.", author: "Don DeLillo", source: "White Noise", difficulty: 1)
p8 = Puzzle.create(content: "He couldn't figure out if she was immensely well adjusted or seriously messed up.", author: "Jonathan Franzen", source: "The Corrections", difficulty: 1)
p9 = Puzzle.create(content: "You never know what worse luck your bad luck has saved you from.", author: "Cormac McCarthy", source: "No Country For Old Men", difficulty: 1)
p10 = Puzzle.create(content: "Scars have the strange power to remind us that our past is real.", author: "Cormac McCarthy", source: "All the Pretty Horses", difficulty: 1)
p11 = Puzzle.create(content: "One of the mixed blessings of being twenty and twenty-one and even twenty-three is the conviction that nothing like this, all evidence to the contrary notwithstanding, has ever happened before.", author: "Joan Didion", source: "Slouching Towards Bethlehem", difficulty: 1)
p12 = Puzzle.create(content: "You might be poor, your shoes might be broken, but your mind is a palace.", author: "Frank McCourt", source: "Angela's Ashes", difficulty: 1)
p13 = Puzzle.create(content: "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.", author: "Henry David Thoreau", source: "Walden", difficulty: 1)
p14 = Puzzle.create(content: "You will become way less concerned with what other people think of you when you realize how seldom they do.", author: "David Foster Wallace", source: "Infinite Jest", difficulty: 1)

Challenge.create(user: bob, puzzle: p1)
Challenge.create(user: bob, puzzle: p2)
Challenge.create(user: nash, puzzle: p4)
Challenge.create(user: nash, puzzle: p5)